#!/bin/bash

#Welcome Message
echo "Welcome to the Directory Storage Utilization Report Tool."
echo "Version 1.0"
echo "Created by Jason Verzonilla"
sleep 1

#Define Report and File Details
read -p "Enter the directory that you would like to generate the report for: " dirReport
sleep 1
read -p "Enter the absolute path in which you'll save the report: " absolutePath
sleep 1
read -p "Enter the desired file name for the report (Name Only): " reportFile

finalReport=$absolutePath/$reportFile.txt

#Generate the report
echo "--------Report Start-------" >> $finalReport
echo "This report was generated by $(whoami) on $(date)" >> $finalReport
echo "-------Report Details-------" >> $finalReport
sudo du -sh $dirReport >> $finalReport

#If the last command (Signified by $? which is the exit code of the last file) ended in an exit code of 0 (Success), then...
if [ $? = 0 ];then
	echo "Report generation was successful. Your report is located here in: $finalReport";echo "--------------Report Complete-------------" >> $finalReport
else
	echo "An error occurred during file generation. Try again. Exit code: $?"
fi
